---
- hosts: board
  gather_facts: false
  vars:
  tasks:
  - name: Install tools
    apt: name={{ item }} state=latest
    with_items:
      - wget
      - git
      - tree
      - htop
      - tmux
      - iotop
      - iftop
      - mc
      - curl
      - links2
      - net-tools
      - iptraf
      - nmap
      - ethtool
      - telnet
      - screen
      - mosh
#      - python3
#      - python3-virtualenv
#      - sysv-rc-conf # not available in Bionic
      - multitail
      - netcat
      - tcpdump
      - figlet
      - toilet
#      - dbus-x11
