---
- hosts: board
  gather_facts: false
  tasks:

  # - name: include secret vars
  #   include_vars:
  #     file: ../secret.yml
  #     # name: secret

  - name: deploy puppeteer scripts
    template:
      src: "{{ item }}"
      dest: "/opt/webscreenbox/puppeteer/"
      owner: "{{ operator_user }}"
      group: "{{ operator_user }}"
      mode: 0755
    with_fileglob:
      - "../puppeteer/example_scroll.js"

    # TODO remove unused scripts not to store secrets, only use the ones from layout

  - name: deploy local browser script
    template:
      src: ../browsers/{{ start_browser_script }}
      dest: "/opt/webscreenbox/start_browser.sh"
      owner: "{{ operator_user }}"
      group: "{{ operator_user }}"
      mode: 0755

  - name: deploy local layout config
    template:
      src: ../layouts/{{ layout }}
      dest: "/opt/webscreenbox/scripted.sh"
      owner: "{{ operator_user }}"
      group: "{{ operator_user }}"
      mode: 0755
