---
- hosts: board
  gather_facts: false
  handlers:
    - name: restart zabbix-agent
      systemd:
        state: restarted
        name: zabbix-agent

  tasks:

  - name: Install software
    apt: name=zabbix-agent state=present

  - name: Zabbix config
    notify: restart zabbix-agent
    copy:
      dest: /etc/zabbix/zabbix_agentd.conf
      content: |
        PidFile=/var/run/zabbix/zabbix_agentd.pid
        LogFile=/var/log/zabbix-agent/zabbix_agentd.log
        LogFileSize=0
        Include=/etc/zabbix/zabbix_agentd.conf.d/*.conf

        Server={{ zabbix_server }}
        ServerActive={{ zabbix_server }}
        HostMetadataItem=system.uname

  - name: ensure zabbix-agent is running and auto-start enabled
    systemd:
      name: zabbix-agent
      state: started
      enabled: true
