---
- hosts: board
  gather_facts: false
  handlers:
    - name: restart snmpd
      systemd:
        state: restarted
        name: snmpd

  tasks:

    - name: Install snmpd
      apt: name={{ item }} state=present
      with_items:
        - net-snmp
        - net-snmp-utils

    - name: Ensure snmpd config is in place
      notify: restart snmpd
      copy:
        dest: /etc/snmp/snmpd.conf
        content: |
          # listen
          agentAddress  udp:161

          # run as
          agentuser  root

          # read-only community
          rocommunity {{ snmp_ro_community }}
        mode: 0600

    - name: ensure snmpd is running and auto-start enabled
      systemd:
        state: started
        name: snmpd
        enabled: true
