---
- hosts: board
  gather_facts: false
  tasks:
  - name: reboot
    shell: reboot
    async: 0
    poll: 0

  # TODO maybe better
  # - name: Restart server
  #   shell: sleep 3s ; /sbin/shutdown -r now
  #   async: 0
  #   poll: 0
  #   ignore_errors: true
  #
  # - name: Wait for the server to finish rebooting
  #   sudo: no
  #   local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
